Repository reebr/challenge-stats, pull requests merged in 2019-10, with the labels that each got.

#16 Substituição imagem para midias sociais
  public/imagem.jpg
Labels: 💅 Layout

#14 Removed the pull request's author from "unique reactions" counter
  src/components/pullrequest/PullRequest.vue
  src/components/reaction/Reactions.vue
  src/lib/helpers.js
  tests/unit/components/reaction/reactions.spec.js
  tests/unit/lib/helpers.spec.js
Labels: 🏗 Enhancement

#21 Fixed the formatting of dates past more than one month
  src/lib/datetime.js
  tests/unit/lib/datetime.spec.js
Labels: 🐞 Bug

#15 Added badges for winners on participants list
  jest.config.js
  src/components/challenge/Challenge.vue
  src/components/pullrequest/PullRequest.vue
  src/components/pullrequest/PullRequests.vue
  src/components/pullrequest/pull-request.styl
  src/components/pullrequest/pull-requests.styl
  src/components/winner/Winner.vue
  src/components/winner/Winners.vue
  src/components/winner/winner.styl
  src/components/winner/winners.styl
  tests/unit/components/pullrequest/pullrequest.spec.js
  tests/unit/components/pullrequest/pullrequests.spec.js
  tests/unit/components/winner/winner.spec.js
  tests/unit/components/winner/winners.spec.js
Labels: 🏗 Enhancement
